name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/bun@v1
        with:
          bun-version: 'latest' # or specify a version like '0.6.13'

      - name: Install dependencies with Bun
        run: bun install

      - name: Build Vite project with Bun
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
